# alias docker='sudo docker'
alias grep='grep --colour=auto'
alias jo='jobs -l'
alias k='kubectl'
alias l='ls -C --classify'
alias la='ls --almost-all --human-readable -l'
alias ll='ls --human-readable -l'
alias ngrep='grep --colour=auto --exclude-dir=.git --exclude-dir=dist --exclude-dir=node_modules --exclude-dir=target'
alias oc='kubectl'
# alias ping='ping -c 4'
alias tmux='tmux -u'
alias up='uptime'
alias vi='vim'
