# alias docker='sudo docker'
alias grep='grep --colour=auto'
alias jo='jobs -l'
alias l='ls -C --classify'
alias la='ls --almost-all --human-readable -l'
alias ll='ls --human-readable -l'
alias oc='kubectl'
# alias ping='ping -c 4'
alias please='sudo $(fc -ln -1)'
alias tmux='tmux -u'
alias up='uptime'
alias vi='vim'
